FROM node:15.7.0-alpine3.10
USER root
RUN apk add udev ttf-freefont chromium git
ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD true
ENV CHROMIUM_PATH /usr/bin/chromium-browser

RUN mkdir /home/node/app

WORKDIR /home/node/app

COPY package*.json ./

RUN npm install
COPY --chown=node:node . .
COPY startup.sh /home/node/app/startup.sh
CMD [ "sh","/home/node/app/startup.sh"]
